# Generated by Django 6.1 on 2026-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_pipeline_tag_profile_updated_at_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='crmApp_comp_name_47a735_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='crmApp_comp_industr_ae0632_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='crmApp_comp_country_af5146_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crmApp_cont_last_na_49cb5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crmApp_cont_email_cf6fdb_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='crmApp_cont_phone_880f02_idx',
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('inactive', 'Inactive')], default='lead', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tags',
        ),
    ]
